# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h18AMQ_lsqdDuAPVI9Am7JXiyRlgEOoQ
"""

# CELL 1 - Install
!pip install -q transformers sentence-transformers faiss-cpu
!pip install -q -U sentence-transformers huggingface_hub
!pip install -q -U langchain-text-splitters

# CELL 2 - Chunking
import os
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Load our document
with open("my_knowledge.txt") as f:
    knowledge_text = f.read()
# 1. Initialize the Text Splitter
# This splitter is smart. It tries to split on paragraphs ("\n\n"),
# then newlines ("\n"), then spaces (" "), to keep semantically
# related text together as much as possible.
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=150, # Max size of a chunk
    chunk_overlap=20,# Overlap to maintain context between chunks
    length_function=len
)
# 2. Create the chunks
chunks = text_splitter.split_text(knowledge_text)

print(f"We have {len(chunks)} chunks:")
for i, chunk in enumerate(chunks):
    print(f"--- Chunk {i+1} ---\n{chunk}\n")

# CELL 3 - Embeddings
from sentence_transformers import SentenceTransformer
# 1. Load the embedding model
# 'all-MiniLM-L6-v2' is a fantastic, fast, and small model.
# It runs 100% on your local machine.
model = SentenceTransformer('all-MiniLM-L6-v2')
chunk_embeddings = model.encode(chunks)
# 2. Embed all our chunks
# This will take a moment as it "reads" and "understands" each chunk.
print(f"Shape of our embeddings: {chunk_embeddings.shape}")

# CELL 4 - FAISS Index
import faiss
import numpy as np
# Get the dimension of our vectors (e.g., 384)
d = chunk_embeddings.shape[1]
# 1. Create a FAISS index
# IndexFlatL2 is the simplest, most basic index. It calculates
# the exact distance (L2 distance) between our query and all vectors.
index = faiss.IndexFlatL2(d)
# 2. Add our chunk embeddings to the index
# We must convert to float32 for FAISS
index.add(np.array(chunk_embeddings).astype('float32'))

print(f"FAISS index created with {index.ntotal} vectors.")

from transformers import T5ForConditionalGeneration, T5Tokenizer
import torch
# 1. Load a "Question-Answering" or "Text-Generation" model
# We'll use a small, instruction-tuned model from Google.
tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-small")
t5_model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-small")

print("Model loaded successfully.")

# --- This is our RAG pipeline function ---

def answer_question(query):
    # 1. RETRIEVE
    # Embed the user's query
    query_embedding = model.encode([query]).astype('float32')
    # Search the FAISS index for the top k (e.g., k=2) most similar chunks
    k=2
    distances, indices = index.search(query_embedding, 2)

    # Get the actual text chunks from our original 'chunks' list

    retrieved_chunks = [chunks[i] for i in indices[0]]
    context = "\n\n".join(retrieved_chunks)

    # 2. AUGMENT
    # This is the "magic prompt." We combine the retrieved context
    # with the user's query.
    prompt_template = f"""
    Answer the following question using *only* the provided context.
    If the answer is not in the context, say "I don't have that information."

    Context:
    {context}

    Question:
    {query}

    Answer:
    """

    # 3. GENERATE (KEY FIX)
    # Feed the augmented prompt to our generative model
    inputs = tokenizer(prompt_template, return_tensors="pt",
                       truncation=True, max_length=512)
    with torch.no_grad():
        outputs = t5_model.generate(**inputs, max_new_tokens=100)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    print(f"--- CONTEXT ---\n{context}\n")
    return answer

query_1 = "What is the WFH policy?"
print(f"Query: {query_1}")
print(f"Answer: {answer_question(query_1)}\n")

query_2 = "What is the company's dental plan?"
print(f"Query: {query_2}")
print(f"Answer: {answer_question(query_2)}\n")